---

# tasks file for faba.useraccounts

  - name: "Include Distro specific vars"
    include_vars: "{{ inventory_dir }}/vars/distros/{{ ansible_lsb.id }}.yml"
  - include_vars: "{{user_var_file}}"

  - name: "Install required Shells"
    apt:
      package: "{{ item.shell }}"
      state: present
    with_items: "{{ users }}"

  - name: "Install Sudo"
    apt:
      package: sudo
      state: present
      update_cache: yes

  - name: "Create Groups"
    group:
      name: "{{ item.1 }}"
      state: present
    with_subelements:
      - "{{ users }}"
      - groups

  - name: "Create Users"
    user:
      name: "{{ item.0.name }}"
      password: "{{ item.0.password }}"
      groups: "{{ item.1 }}"
      append: yes
      shell: "/bin/{{ item.0.shell }}"
    with_subelements:
      - "{{ users }}"
      - groups

  - name: "Added ssh key"
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ lookup('file', '{{ item.sshkey }}') }}"
    become: yes
    with_items: "{{ users }}"

  # - name: "Copy files"
  #   copy:
  #     src: "{{ item.name }}/"
  #     dest: "/home/{{ item.name }}"
  #     owner: "{{ item.name }}"
  #     group: "{{ item.name }}"
  #   with_items: "{{ users }}"
  #   tags: copy_files